name: deploy to lambda
on: [push]

jobs:

    deploy_source:
        name: Daily shutdown
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: default deploy
              uses: appleboy/lambda-action@v0.2.0
              with:
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
                  aws_region: ${{ secrets.AWS_DEFAULT_REGION}}
                  function_name: daily_shutdown
                  source: src/main.py
                  #ZIP_FILE: my-function.zip
                  timeout: 300
                  memory_size: 128
                  runtime: python3.13
                  role: arn:aws:iam::123456789012:role/service-role/daily_shutdown-role-olcgws61
                  
